server:
  port: 8888
eureka:
#  server:
#    enable-self-preservation: false
#    eviction-interval-timer-in-ms: 4000 # This is not required
  instance:
    hostname: localhost
#    ip-address: 127.0.0.1
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://alan:alan@${eureka.instance.hostname}:${server.port}/eureka/
spring:
  security:
    user:
      name: alan
      password: alan